### ISSUE TITLE
Update improper package names

### ISSUE THREAD

**Issue by LPK-Matt** [MatthewSH/minecraft-Huzuni#6]
Since the original client was hosted on Hal's .net domain it used the following package:

```java
package net.halalaboos.huzuni;
```

But since this is no longer the case it would be proper to refactor the package names. Since you own [matthewhatcher.com](https://matthewhatcher.com/) I would recommend the following:

```java
package com.matthewwhatcher.huzuni;
```

**Comment by MatthewSH** [comment]
That's not something I can do. The code was open sourced by Hal, and was written by Hal. I can't take credit for his code. I'm only maintaining it and adding new stuff.

**Comment by LPK-Matt** [comment]
According to Oracle's documentation on java [naming packages based on your domain is proper syntax to use](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). If Hal did not own his own .net domain he would have used `me.halalaboos.huzuni` or another non-domain based prefix package.

**Comment by MatthewSH** [comment]
Well, I'm not worrying about commenting anything as it's just a client. I'm just fixing this and that. Whatever I add will be in my own package.

**Comment by nerd** [comment]
if it doesn't deserve a package restructure then it doesn't deserve to be a fork, just pull request the original.


oh wait you can't make profit from that
