### ISSUE TITLE
Remove donations from repo/client to stay within Mojang EULA

### ISSUE THREAD

**Issue by LPK-Matt** [MatthewSH/minecraft-Huzuni#7]
As per [the Mojang EULA](https://account.mojang.com/documents/minecraft_eula):

> **Essentially the simple rule is do not make commercial use of anything we've made unless we've specifically said it's okay**. Oh and if the law expressly allows it, such as under a "fair use" or fair dealing" doctrine then that's ok too - but only to the extent that the law applicable to you says so.

It can be on your personal website but is not allowed to be associated with Mojang's intellectual property.

**Comment by MatthewSH** [comment]
The donations are associated with CapesAPI, not the client itself.
